# Generated by Django 4.1.2 on 2022-10-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')])),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('type', models.IntegerField(choices=[(0, 'Noun'), (1, 'Pronoun'), (2, 'Verb'), (3, 'Adjective'), (4, 'Adverb'), (5, 'Preposition'), (6, 'Conjuction'), (7, 'Interjection')])),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.word')),
            ],
        ),
    ]
