# Generated by Django 4.1.2 on 2022-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='username', max_length=128),
            preserve_default=False,
        ),
    ]
